name: CyRadar

on:
  push:
    branches:
      - '*'

jobs:
  run-jupyter-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y graphviz
          pip install ipython nbconvert jupyter

      - name: Converting Jupyter Notebook
        run: jupyter nbconvert cyradar_model/spam-detection.ipynb --to python

      - name: Install dependencies from requirement file
        run: pip install -r cyradar_model/requrement.txt
      - name: Run the CyRadar
        run: python cyradar_model/spam-detection.py
        
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Latest Release
          tag_name: LatestRelease
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cyradar_model/model.h5
          asset_name: cyradar-model.h5
          asset_content_type: application/binary
