name: CyRadar

on:
  push:
    branches:
      - '*'

jobs:
  run-jupyter-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 

    - name: Install dependencies
      run: pip install papermill nbconvert
    
    - name: Install dependencies from requrement file
      run: pip install -r cyradar_model/requrement.txt
      
    - name: Run Jupyter Notebook
      run: papermill cyradar_model/spam-detection.ipynb output.ipynb
    

    - name: Convert to HTML (optional)
      run: jupyter nbconvert --to html output.ipynb
